import '../model/profile_model.dart';

class ProfileRepository {
  final List<ProfileModel> _profiles = [
    ProfileModel(
      name: 'Starlink',
      username: '@starlink',
      bio: 'Satellite internet by SpaceX 🌍',
      imageUrl: 'https://example.com/starlink.jpg',
      isVerified: true,
      stateFollow: ProfileStateOfFollow.following,
      stateMute: ProfileStateOfMute.notmuted,
      stateBlocked: ProfileStateBlocked.notblocked,
    ),
    ProfileModel(
      name: 'Tesla',
      username: '@tesla',
      bio: 'Electric vehicles and clean energy ⚡',
      imageUrl: 'https://example.com/tesla.jpg',
      isVerified: true,
      stateFollow: ProfileStateOfFollow.following,
      stateMute: ProfileStateOfMute.notmuted,
      stateBlocked: ProfileStateBlocked.notblocked,
    ),
    ProfileModel(
      name: 'spaceX',
      username: '@spacex',
      bio: 'Making life multiplanetary 🚀',
      imageUrl: 'https://example.com/spacex.jpg',
      isVerified: false,
      stateFollow: ProfileStateOfFollow.following,
      stateMute: ProfileStateOfMute.notmuted,
      stateBlocked: ProfileStateBlocked.notblocked,
    ),
    ProfileModel(
      name: 'Neuralink',
      username: '@neuralink',
      bio: 'Brain-machine interfaces 🧠',
      imageUrl: 'https://example.com/neuralink.jpg',
      isVerified: false,
      stateFollow: ProfileStateOfFollow.following,
      stateMute: ProfileStateOfMute.notmuted,
      stateBlocked: ProfileStateBlocked.notblocked,
    ),
    ProfileModel(
      name: 'The Boring',
      username: '@boringcompany',
      bio: 'Tunnel construction and infrastructure 🚇',
      imageUrl: 'https://example.com/boringcompany.jpg',
      isVerified: false,
      stateFollow: ProfileStateOfFollow.following,
      stateMute: ProfileStateOfMute.notmuted,
      stateBlocked: ProfileStateBlocked.notblocked,
    ),
    ProfileModel(
      name: 'OpenAI',
      username: '@openai',
      bio: 'Advancing digital intelligence for humanity 🤖',
      imageUrl: 'https://example.com/openai.jpg',
      isVerified: true,
      stateFollow: ProfileStateOfFollow.following,
      stateMute: ProfileStateOfMute.notmuted,
      stateBlocked: ProfileStateBlocked.notblocked,
    ),
    ProfileModel(
      name: 'DeepMind',
      username: '@deepmind',
      bio: 'AI research and applications 🧠',
      imageUrl: 'https://example.com/deepmind.jpg',
      isVerified: true,
      stateFollow: ProfileStateOfFollow.following,
      stateMute: ProfileStateOfMute.notmuted,
      stateBlocked: ProfileStateBlocked.notblocked,
    ),
    ProfileModel(
      name: 'Anthropic',
      username: '@anthropic',
      bio: 'AI safety and research lab 🔬',
      imageUrl: 'https://example.com/anthropic.jpg',
      isVerified: false,
      stateFollow: ProfileStateOfFollow.following,
      stateMute: ProfileStateOfMute.notmuted,
      stateBlocked: ProfileStateBlocked.notblocked,
    ),
    ProfileModel(
      name: 'Cohere',
      username: '@cohere',
      bio: 'Natural language processing models 🗣️',
      imageUrl: 'https://example.com/cohere.jpg',
      isVerified: false,
      stateFollow: ProfileStateOfFollow.following,
      stateMute: ProfileStateOfMute.notmuted,
      stateBlocked: ProfileStateBlocked.notblocked,
    ),
    ProfileModel(
      name: 'Hugging Face',
      username: '@huggingface',
      bio: 'Building the future of machine learning 🤗',
      imageUrl: 'https://example.com/huggingface.jpg',
      isVerified: true,
      stateFollow: ProfileStateOfFollow.following,
      stateMute: ProfileStateOfMute.notmuted,
      stateBlocked: ProfileStateBlocked.notblocked,
    ),
    ProfileModel(
      name: 'Stability AI',
      username: '@stabilityai',
      bio: 'Democratizing AI for all 🌐',
      imageUrl: 'https://example.com/stabilityai.jpg',
      isVerified: false,
      stateFollow: ProfileStateOfFollow.following,
      stateMute: ProfileStateOfMute.notmuted,
      stateBlocked: ProfileStateBlocked.notblocked,
    ),
    ProfileModel(
      name: 'Runway',
      username: '@runway',
      bio: 'Creative tools powered by AI 🎨',
      imageUrl: 'https://example.com/runway.jpg',
      isVerified: false,
      stateFollow: ProfileStateOfFollow.following,
      stateMute: ProfileStateOfMute.notmuted,
      stateBlocked: ProfileStateBlocked.notblocked,
    ),
    ProfileModel(
      name: 'MidJourney',
      username: '@midjourney',
      bio: 'AI-generated art and creativity 🖼️',
      imageUrl: 'https://example.com/midjourney.jpg',
      isVerified: false,
      stateFollow: ProfileStateOfFollow.following,
      stateMute: ProfileStateOfMute.notmuted,
      stateBlocked: ProfileStateBlocked.notblocked,
    ),
  ];
  

  List<ProfileModel> getProfiles() => _profiles;
}
